---
title: "Visualisation des attaques des requins de 1930 à 2018"
author: "Marie-Pierre Etienne"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Moodle", href: "https://tice.agrocampus-ouest.fr/course/view.php?id=6726", align: left }
      - { icon: "fa-twitter", href: "https://twitter.com/marie_etienne", align: right }
      - { icon: "fa-link", title: "Dataset", href: "https://www.kaggle.com/datasets/felipeesc/shark-attack-dataset", align: right }
params:
  setup_path: ../resources/
---

<style>                     
.navbar {
  background-color:#46ACC8;
  border-color:#46ACC8;
}
.navbar-brand {
color:black!important;
}


</style>   


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### An easy solution for dashboard

```{r, echo = TRUE}
#install.package('flexdasboard')
#rmarkdown::draft("dashboard.Rmd", template = "flex_dashboard", package = "flexdashboard")
```

The [flexdashboard website](https://rmarkdown.rstudio.com/flexdashboard/index.html) provides multiple advanced examples.

### Some static graph

```{r data, eval = TRUE, echo = FALSE, results='hide', message = FALSE, warning=FALSE}
n <- 100
dta <- tibble(size = round(rnorm(n, mean = 0, sd =10),2), 
           color = sample(x= c('Blue', 'Yellow'), size = n, replace = TRUE))

```


```{r graph_static,  echo = FALSE,  message = FALSE, warning=FALSE}
p1 <- dta %>% ggplot() +
  aes(x=color, y = size) +
  geom_boxplot(aes(fill= color))
p1
```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------


### Some dynamic maps

```{r  ggplotly, echo = TRUE,  eval = TRUE,  message = FALSE, warning=FALSE}
plotly::ggplotly(p1)
```



### Chart C

```{r}

```

Distribution des Types d'attaques
=======================================================================

Column 
-------------------------------------

```{r}
requin <- read.csv("attacks.csv") 
dim(requin) #  25723    24

req <- requin %>% 
  select("Date","Year", "Type", "Country", "Area","Activity", "Fatal..Y.N.") %>%
  filter(Year >= 1930)
#nbr des attaques par annee
val <- req3 %>% count(Year,Type, sort = TRUE)
#Types of attacks
val[val=="Boating"]<-NA
val <- val %>%
  mutate_at(c('Type'), ~replace_na(.,"Boat"))
#
val[val==""]<-NA
val <- val %>%
  mutate_at(c('Type'), ~replace_na(.,"Boat"))
#graph
nbatq <- ggplot(val, aes(Year,n), alpha= Country ) + geom_line(aes( color=Type))+ggtitle("Evolution des attaques des requins pour les 3 premiers Pays") +ylab("Nb Attaques") + xlab("Année")+theme(plot.title = element_text(face="bold",color = "#607c8e", size = 15, hjust=0.5,vjust=1, family = "Serif"),
                       legend.position = c(0.2, 0.8),
                       axis.title.x = element_text( face = "bold",size=10),
                       axis.title.y = element_text(face = "bold",size=10),
                       panel.background = element_rect(fill = "white"),
                       panel.grid.major = element_blank()
                       ) +scale_y_continuous(breaks = seq(0, 88, by = 10))

ggplotly(nbatq)
```


Column 
-------------------------------------
   
   
```{r}
typ2 <- req3  %>% group_by(Country) %>% count(Year,Type, sort = TRUE)
#
typ2[typ2=="Boating"]<-NA
typ2 <- typ2 %>%
  mutate_at(c('Type'), ~replace_na(.,"Boat"))
#
typ2[typ2==""]<-NA
typ2 <- typ2 %>%
  mutate_at(c('Type'), ~replace_na(.,"Boat"))

ggplot(typ2, aes(x=Type, y=n, fill=Country)) +geom_boxplot(outlier.shape=NA)+
  scale_fill_manual(values=c("darkgoldenrod1","darkred", "#002868")) + ylab("Nb Attaques")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1), panel.background = element_rect(fill = "white"),
                       panel.grid.major = element_line(colour = "#bababa"))+ scale_y_continuous(breaks = seq(0, 88, by = 10))  +ggtitle(" Distribution Types d'attaques par Pays")
```