---
title: "sharks"
author: "Atraoui Chaimaa, Laurence Ren"
date: "2022-11-16"
output: html_document
---

Importation des packages.

```{r}
library(ggplot2)
library(tidyverse)
library(wesanderson)
library(dplyr)
library(plotly)
library("dplyr")
library("tidyr")
library(flexdashboard)
```

## mise en forme du jeu de donnée 
```{r}

requin <- read.csv("attacks.csv") 
dim(requin) #  25723    24

req <- requin %>% 
  select("Date","Year", "Type", "Country", "Area","Activity", "Fatal..Y.N.") %>%
  filter(Year >= 1930) 
req3<- req[req$Country %in% c("USA","AUSTRALIA", "SOUTH AFRICA"),]
dim(req) # 5054    6

sum(is.na(req)) # 0 donc pas de na 


#total des attaques par année. visualisation temporelle par type. 


#nbr des attaques par annee
val <- req3 %>% count(Year,Type, sort = TRUE)
##nbr des attaques par annee pour chque type
typ2 <- req3  %>% group_by(Country) %>% count(Year,Type, sort = TRUE)
typ[typ==""]<-NA
typ <- typ %>%
  mutate_at(c('Type'), ~replace_na(.,"Unknown"))

##nbr des attaques par  pour chque type
total <- typ %>% count(Type,n, sort = TRUE)

# Fatality 
req[req==""]<-NA
req <- req %>%
  mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"Unknown"))
#
req[req=="UNKNOWN"]<-NA
req <- req %>%
  mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"Unknown"))
#
req[req=="Unknown"]<-NA
req <- req %>%
  mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"M"))
#
req[req==" N"]<-NA
req <- req %>%
  mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"N"))
#
req[req=="2017"]<-NA
req <- req %>%
  mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"Y"))


#Types of attacks
val[val=="Boating"]<-NA
val <- val %>%
  mutate_at(c('Type'), ~replace_na(.,"Boat"))
#
val[val==""]<-NA
val <- val %>%
  mutate_at(c('Type'), ~replace_na(.,"Boat"))
#
typ2[typ2=="Boating"]<-NA
typ2 <- typ2 %>%
  mutate_at(c('Type'), ~replace_na(.,"Boat"))
#
typ2[typ2==""]<-NA
typ2 <- typ2 %>%
  mutate_at(c('Type'), ~replace_na(.,"Boat"))
```


##1-evolution des attaques par annees (count)
<!-- #scale_fill_manual(values = c( #palette personnalisée -->
<!--                          'Boat' = "#76C223", -->
<!--                          'Invalid' = "#76C223", -->
<!--                          'Provoked' = "#76C223", -->
<!--                          'Questionable' = "#76C223", -->
<!--                          'Sea Disaster' = "#76C223", -->
<!--                          'Unprovoked' = "#76C223"), name = '') -->

```{r}

nbatq <- ggplot(val, aes(Year,n), alpha= Country ) + geom_line(aes( color=Type))+ggtitle("Evolution des attaques des requins pour les 3 premiers Pays") +ylab("Nb Attaques") + xlab("Année")+theme(plot.title = element_text(face="bold",color = "#607c8e", size = 15, hjust=0.5,vjust=1, family = "Serif"),
                       legend.position = c(0.2, 0.8),
                       axis.title.x = element_text( face = "bold",size=10),
                       axis.title.y = element_text(face = "bold",size=10),
                       panel.background = element_rect(fill = "white"),
                       panel.grid.major = element_blank()
                       ) +scale_y_continuous(breaks = seq(0, 88, by = 10))

ggplotly(nbatq)
```
```{r}

ggplot(typ2, aes(x=Type, y=n, fill=Country)) +geom_boxplot(outlier.shape=NA)+
  scale_fill_manual(values=c("darkgoldenrod1","darkred", "#002868")) + ylab("Nb Attaques")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1), panel.background = element_rect(fill = "white"),
                       panel.grid.major = element_line(colour = "#bababa"))+ scale_y_continuous(breaks = seq(0, 88, by = 10))  +ggtitle(" Distribution Types d'attaques par Pays")
```



<!-- ##graphe évolution par année des attaques  -->

<!-- ```{r} -->
<!-- # Data transformation -->

<!-- df <- typ %>%  -->
<!--   group_by(Type) %>% # Variable to be transformed -->
<!--   count() %>%  -->
<!--   ungroup() %>%  -->
<!--   mutate(perc = `n` / sum(`n`)) %>%  -->
<!--   arrange(perc) %>% -->
<!--   mutate(labels = scales::percent(perc)) -->
<!-- pie <- ggplot(df, aes(x = "", y = perc, fill = Type)) + -->
<!--   geom_col(color = "black") + -->
<!--   geom_text(aes(label = labels), -->
<!--             position = position_stack(vjust = 0.5)) + -->
<!--   coord_polar(theta = "y") + scale_fill_brewer() -->


<!-- #ggplotly(pie) -->
<!-- ``` -->


<!-- ```{r} -->

<!-- data <- total %>% count(Type, wt = nn) -->
<!-- names(data)[names(data) == "n"] <- "count" -->


<!-- blank_theme <- theme_minimal()+ -->
<!--   theme( -->
<!--     axis.title.x = element_blank(), -->
<!--     axis.title.y = element_blank(), -->
<!--     panel.border = element_blank(), -->
<!--     panel.grid=element_blank(), -->
<!--     axis.ticks = element_blank(), -->
<!--     plot.title=element_text(size=14, face="bold") -->
<!--   ) -->


<!-- # Compute percentages -->
<!-- data$fraction <- data$count / sum(data$count) -->

<!-- # Compute the cumulative percentages (top of each rectangle) -->
<!-- data$ymax <- cumsum(data$fraction) -->

<!-- # Compute the bottom of each rectangle -->
<!-- data$ymin <- c(0, head(data$ymax, n=-1)) -->

<!-- #perc -->
<!-- data$Type <-factor(data$Type, levels = c ("Boat","Invalid","Provoked","Questionable","Sea Disaster","Unknown","Unprovoked")) -->
<!-- # Compute label position -->
<!-- #data$labelPosition <- (data$ymax + data$ymin) / 2 -->

<!-- # Compute a good label -->
<!-- #data$label <- paste0(data$Type, "\n value: ", data$count) -->

<!-- # Make the plot -->
<!-- p1 <- ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=Type)) + -->
<!--   geom_rect(color='blue') + -->
<!--   #geom_label( x=3.5, aes(y=labelPosition, label=label), size=6) + -->
<!--   #scale_fill_brewer(palette=4) + -->
<!--   coord_polar(theta="y")  -->
<!--   #xlim(c(2, 4)) + -->
<!--   #theme_void() + -->
<!--   #theme(legend.position = "none") -->

<!-- edu<-p1 + scale_fill_brewer("Type") + blank_theme + -->
<!--   theme(axis.text.x=element_blank()) + theme(legend.position=c(.5, .5)) + ggtitle("") + -->
<!--   theme(panel.grid=element_blank()) + -->
<!--   theme(axis.text=element_blank()) + -->
<!--   theme(axis.ticks=element_blank()) + -->
<!--   theme(legend.title = element_text(size=16, face="bold")) + -->
<!--   theme(legend.text = element_text(size = 14, face = "bold")) -->

<!-- edu + -->
<!--   geom_label( -->
<!--     aes(label = paste(fraction * 100, "%"), -->
<!--     x = 3.5, -->
<!--     y = (ymin + ymax) / 2), -->
<!--     inherit.aes = TRUE, -->
<!--     show.legend = FALSE -->
<!--   ) -->
<!-- edu -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # colors <- c('rgb(211,94,96)', 'rgb(128,133,133)', 'rgb(144,103,167)', 'rgb(171,104,87)', 'rgb(114,147,203)') -->
<!-- #  -->
<!-- # fig <- plot_ly(df, labels = ~Type, values = ~perc, type = 'pie', -->
<!-- #         textposition = 'inside', -->
<!-- #         textinfo = 'label+percent', -->
<!-- #         insidetextfont = list(color = '#FFFFFF'), -->
<!-- #         hoverinfo = 'text', -->
<!-- #         text = ~paste('', n, ' attaques'), -->
<!-- #         marker = list(colors = colors, -->
<!-- #                       line = list(color = '#FFFFFF', width = 1)), -->
<!-- #                       #The 'pull' attribute can also be used to create space between the sectors -->
<!-- #         showlegend = FALSE) -->
<!-- # fig <- fig %>% layout(title = 'Pourcentages des attaques par type de 1930 à 2018)', -->
<!-- #          xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE), -->
<!-- #          yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)) -->
<!-- #  -->
<!-- # fig -->

<!-- ``` -->




<!-- ```{r} -->
<!-- library(scales) -->

<!-- df <- req %>%  -->
<!--   group_by(Fatal..Y.N.) %>% # Variable to be transformed -->
<!--   count() %>%  -->
<!--   ungroup() %>%  -->
<!--   mutate(perc = `n` / sum(`n`)) %>%  -->
<!--   arrange(perc) %>% -->
<!--   mutate(labels = scales::percent(perc)) -->
<!-- pie <- ggplot(df, aes(x = "", y = perc, fill = Fatal..Y.N.)) + -->
<!--   geom_col(color = "black") + -->
<!--   geom_text(aes(label = labels), -->
<!--             position = position_stack(vjust = 0.5)) + -->
<!--   coord_polar(theta = "y")  + scale_fill_brewer("Fatality") +   -->
<!--   theme(axis.text.x=element_blank()) -->

<!-- pie + scale_fill_manual(values =wes_palette("Royal1")) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- requin <- read.csv("attacks.csv")  -->


<!-- ## choisir les colonnes d'intérêt -->
<!-- req <- requin %>% -->
<!--   select("Year", "Type", "Country", "Area","Activity", "Fatal..Y.N.") %>% -->
<!--   filter(Year >= 1930) -->

<!-- req_pie <- req %>%  -->
<!--   select("Type",  "Fatal..Y.N.", "Activity") -->
<!-- # diving  -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("diving", req_pie$Activity[i]) | (grepl("Diving", req_pie$Activity[i])) | -->
<!--       (grepl("Dived", req_pie$Activity[i]))) { -->
<!--     req_pie$Activity[i] <- "Diving" -->
<!--   }  -->
<!-- } -->

<!-- # fishing -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("fishing", req_pie$Activity[i]) | (grepl("Fishing", req_pie$Activity[i])) | -->
<!--       (grepl("lobsters", req_pie$Activity[i])) | -->
<!--       grepl("fish", req_pie$Activity[i]) | -->
<!--       grepl("bichiques", req_pie$Activity[i]) -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "fishing" -->
<!--   }  -->
<!-- } -->

<!-- # air or sea disaster -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("disaster", req_pie$Activity[i]) | grepl("Disaster", req_pie$Activity[i])|  -->
<!--       (grepl("air", req_pie$Activity[i])) | (grepl("plane", req_pie$Activity[i])) -->
<!--       | (grepl("757", req_pie$Activity[i]))| -->
<!--       grepl("hurricane", req_pie$Activity[i]) -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "Air/Sea disaster" -->
<!--   }  -->
<!-- } -->

<!-- # boat/ship accident de bateau  -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("Boat", req_pie$Activity[i]) | (grepl("boat", req_pie$Activity[i])) -->
<!--       | (grepl("ship", req_pie$Activity[i])) | (grepl("Fell", req_pie$Activity[i])) -->
<!--       | (grepl("Vessel", req_pie$Activity[i])) | -->
<!--       grepl("sank", req_pie$Activity[i])| -->
<!--       grepl("promotional film ", req_pie$Activity[i]) | -->
<!--       grepl("Ferry", req_pie$Activity[i])| -->
<!--       grepl("ferry", req_pie$Activity[i])| -->
<!--       grepl("capsiz", req_pie$Activity[i]) | -->
<!--       grepl("MV Dona Marilyn", req_pie$Activity[i]) | -->
<!--       grepl("schooner Elizabeth", req_pie$Activity[i]) | -->
<!--       grepl("Towing", req_pie$Activity[i]) | -->
<!--       grepl("Tzenny Chandris", req_pie$Activity[i]) | -->
<!--       grepl("Wreck", req_pie$Activity[i]) | -->
<!--       grepl("wreck", req_pie$Activity[i]) | -->
<!--       grepl("dinghy", req_pie$Activity[i]) | -->
<!--       grepl("yacht", req_pie$Activity[i])  -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "boat/ship accident" -->
<!--   }  -->
<!-- } -->

<!-- # sport  -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("surf", req_pie$Activity[i]) | grepl("Surf", req_pie$Activity[i]) |(grepl("boarding", req_pie$Activity[i]))| -->
<!--       grepl("Boarding", req_pie$Activity[i]) | -->
<!--       (grepl("batching", req_pie$Activity[i]))| (grepl("Bathing", req_pie$Activity[i])) | -->
<!--       (grepl("bathing", req_pie$Activity[i])) | -->
<!--       (grepl("Swim", req_pie$Activity[i]))| (grepl("swim", req_pie$Activity[i])) | -->
<!--       (grepl("fell", req_pie$Activity[i])) | (grepl("Paddling", req_pie$Activity[i]))|  -->
<!--       (grepl("Paddling", req_pie$Activity[i])) | (grepl("water", req_pie$Activity[i])) -->
<!--       | (grepl("Snorkeling", req_pie$Activity[i])) -->
<!--       | (grepl("Sitting", req_pie$Activity[i])) |  -->
<!--       grepl("Happy Jack", req_pie$Activity[i]) | -->
<!--       grepl("Bending", req_pie$Activity[i]) | -->
<!--       grepl("Canoe", req_pie$Activity[i]) | -->
<!--       grepl("paddling", req_pie$Activity[i]) | -->
<!--       grepl("Kayak", req_pie$Activity[i]) | -->
<!--       grepl("Lifesaving", req_pie$Activity[i]) | -->
<!--       grepl("Snorkeling", req_pie$Activity[i]) | -->
<!--       grepl("Stamding", req_pie$Activity[i])| -->
<!--       grepl("Wading", req_pie$Activity[i]) | -->
<!--       grepl("Wash", req_pie$Activity[i]) | -->
<!--       grepl("Workong", req_pie$Activity[i])|  -->
<!--       grepl("McIver", req_pie$Activity[i]) | -->
<!--       grepl("Standing", req_pie$Activity[i]) | -->
<!--       grepl("Crossing the bay", req_pie$Activity[i])| -->
<!--       grepl("Walking", req_pie$Activity[i]) | -->
<!--       grepl("kill a shark", req_pie$Activity[i]) | -->
<!--       grepl("Removing shark", req_pie$Activity[i])  -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "sport/ activity" } -->
<!-- } -->



<!-- # adrift -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("Adrift", req_pie$Activity[i]) | grepl("adrift", req_pie$Activity[i]) | -->
<!--       grepl("Floating", req_pie$Activity[i])) { -->
<!--     req_pie$Activity[i] <- "Adrift" -->
<!--   }  -->
<!-- } -->

<!-- # murder /  war  -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("Murder", req_pie$Activity[i]) || -->
<!--       grepl("submarine", req_pie$Activity[i]) | -->
<!--       grepl("American", req_pie$Activity[i]) | -->
<!--       grepl("torpedoed", req_pie$Activity[i]) | -->
<!--       grepl("Torpedoed", req_pie$Activity[i]) | -->
<!--       grepl("soldiers", req_pie$Activity[i]) | -->
<!--       grepl("Escaping", req_pie$Activity[i]) | -->
<!--       grepl("Japanese", req_pie$Activity[i]) | -->
<!--       grepl("Japan", req_pie$Activity[i]) | -->
<!--       grepl("Sinking", req_pie$Activity[i]) | -->
<!--       grepl("SS", req_pie$Activity[i]) | -->
<!--       grepl("foundered", req_pie$Activity[i])  | -->
<!--       grepl("US", req_pie$Activity[i]) -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "murder /  war " -->
<!--   }  -->
<!-- } -->
<!-- # Fatality  -->
<!-- req_pie[req_pie==""]<-NA -->
<!-- req_pie <- req_pie %>% -->
<!--   mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"Unknown")) -->
<!-- # -->
<!-- req_pie[req_pie=="UNKNOWN"]<-NA -->
<!-- req_pie <- req_pie %>% -->
<!--   mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"Unknown")) -->
<!-- # -->
<!-- req_pie[req_pie=="Unknown"]<-NA -->
<!-- req_pie <- req %>% -->
<!--   mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"M")) -->
<!-- # -->
<!-- req_pie[req_pie==" N"]<-NA -->
<!-- req_pie <- req_pie %>% -->
<!--   mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"N")) -->

<!-- req_pie[req_pie=="0"]<-NA -->
<!-- req_pie <- req_pie %>% -->
<!--   mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"M")) -->

<!-- req_pie2[req_pie2==""]<-NA -->
<!-- req_pie2 <- req_pie2 %>% -->
<!--   mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"M")) -->

<!-- req_pie2[req_pie2=="UNKNOWN"]<-NA -->
<!-- req_pie2 <- req_pie2 %>% -->
<!--   mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"M")) -->
<!-- library(ggplot2) -->
<!-- library(webr) -->
<!-- library(dplyr) -->

<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (req_pie$Fatal..Y.N.[i] != "Y") { -->
<!--     req_pie$Activity[i] <- 0 -->
<!--   } -->
<!--   if (req_pie$Type[i] != "Unprovoked") { -->
<!--     req_pie$Fatal..Y.N.[i] <- 0 -->
<!--     req_pie$Activity[i] <- 0 -->
<!--   }  -->
<!-- } -->

<!-- req_pie2 <- req_pie %>%   -->
<!--   group_by(Type, Fatal..Y.N., Activity) %>% -->
<!--   summarise(Effectif = n(), Pourcentage = Effectif/353) -->

<!-- PieDonut(req_pie2, aes(Type, Fatal..Y.N., Activity,Pourcentage)) -->
<!-- ``` -->




<!-- ```{r} -->
<!-- unpro<- req_pie2[9:247,] -->
<!-- unpro[unpro==""]<-NA -->
<!-- unpro <- unpro %>% -->
<!--   mutate_at(c('Fatal..Y.N.'), ~replace_na(.,"UNKNOWN")) -->


<!-- # diving  -->
<!-- for (i in (1:nrow(unpro))) { -->
<!--   if (grepl("diving", unpro$Activity[i]) | (grepl("Diving", req_pie$Activity[i])) | -->
<!--       (grepl("Dived", req_pie$Activity[i]))) { -->
<!--     req_pie$Activity[i] <- "Diving" -->
<!--   }  -->
<!-- } -->

<!-- # fishing -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("fishing", req_pie$Activity[i]) | (grepl("Fishing", req_pie$Activity[i])) | -->
<!--       (grepl("lobsters", req_pie$Activity[i])) | -->
<!--       grepl("fish", req_pie$Activity[i]) | -->
<!--       grepl("bichiques", req_pie$Activity[i]) -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "fishing" -->
<!--   }  -->
<!-- } -->

<!-- # air or sea disaster -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("disaster", req_pie$Activity[i]) | grepl("Disaster", req_pie$Activity[i])|  -->
<!--       (grepl("air", req_pie$Activity[i])) | (grepl("plane", req_pie$Activity[i])) -->
<!--       | (grepl("757", req_pie$Activity[i]))| -->
<!--       grepl("hurricane", req_pie$Activity[i]) -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "Air/Sea disaster" -->
<!--   }  -->
<!-- } -->

<!-- # boat/ship accident de bateau  -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("Boat", req_pie$Activity[i]) | (grepl("boat", req_pie$Activity[i])) -->
<!--       | (grepl("ship", req_pie$Activity[i])) | (grepl("Fell", req_pie$Activity[i])) -->
<!--       | (grepl("Vessel", req_pie$Activity[i])) | -->
<!--       grepl("sank", req_pie$Activity[i])| -->
<!--       grepl("promotional film ", req_pie$Activity[i]) | -->
<!--       grepl("Ferry", req_pie$Activity[i])| -->
<!--       grepl("ferry", req_pie$Activity[i])| -->
<!--       grepl("capsiz", req_pie$Activity[i]) | -->
<!--       grepl("MV Dona Marilyn", req_pie$Activity[i]) | -->
<!--       grepl("schooner Elizabeth", req_pie$Activity[i]) | -->
<!--       grepl("Towing", req_pie$Activity[i]) | -->
<!--       grepl("Tzenny Chandris", req_pie$Activity[i]) | -->
<!--       grepl("Wreck", req_pie$Activity[i]) | -->
<!--       grepl("wreck", req_pie$Activity[i]) | -->
<!--       grepl("dinghy", req_pie$Activity[i]) | -->
<!--       grepl("yacht", req_pie$Activity[i])  -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "boat/ship accident" -->
<!--   }  -->
<!-- } -->

<!-- # sport  -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("surf", req_pie$Activity[i]) | grepl("Surf", req_pie$Activity[i]) |(grepl("boarding", req_pie$Activity[i]))| -->
<!--       grepl("Boarding", req_pie$Activity[i]) | -->
<!--       (grepl("batching", req_pie$Activity[i]))| (grepl("Bathing", req_pie$Activity[i])) | -->
<!--       (grepl("bathing", req_pie$Activity[i])) | -->
<!--       (grepl("Swim", req_pie$Activity[i]))| (grepl("swim", req_pie$Activity[i])) | -->
<!--       (grepl("fell", req_pie$Activity[i])) | (grepl("Paddling", req_pie$Activity[i]))|  -->
<!--       (grepl("Paddling", req_pie$Activity[i])) | (grepl("water", req_pie$Activity[i])) -->
<!--       | (grepl("Snorkeling", req_pie$Activity[i])) -->
<!--       | (grepl("Sitting", req_pie$Activity[i])) |  -->
<!--       grepl("Happy Jack", req_pie$Activity[i]) | -->
<!--       grepl("Bending", req_pie$Activity[i]) | -->
<!--       grepl("Canoe", req_pie$Activity[i]) | -->
<!--       grepl("paddling", req_pie$Activity[i]) | -->
<!--       grepl("Kayak", req_pie$Activity[i]) | -->
<!--       grepl("Lifesaving", req_pie$Activity[i]) | -->
<!--       grepl("Snorkeling", req_pie$Activity[i]) | -->
<!--       grepl("Stamding", req_pie$Activity[i])| -->
<!--       grepl("Wading", req_pie$Activity[i]) | -->
<!--       grepl("Wash", req_pie$Activity[i]) | -->
<!--       grepl("Workong", req_pie$Activity[i])|  -->
<!--       grepl("McIver", req_pie$Activity[i]) | -->
<!--       grepl("Standing", req_pie$Activity[i]) | -->
<!--       grepl("Crossing the bay", req_pie$Activity[i])| -->
<!--       grepl("Walking", req_pie$Activity[i]) | -->
<!--       grepl("kill a shark", req_pie$Activity[i]) | -->
<!--       grepl("Removing shark", req_pie$Activity[i])  -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "sport/ activity" } -->
<!-- } -->



<!-- # adrift -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("Adrift", req_pie$Activity[i]) | grepl("adrift", req_pie$Activity[i]) | -->
<!--       grepl("Floating", req_pie$Activity[i])) { -->
<!--     req_pie$Activity[i] <- "Adrift" -->
<!--   }  -->
<!-- } -->

<!-- # murder /  war  -->
<!-- for (i in (1:nrow(req_pie))) { -->
<!--   if (grepl("Murder", req_pie$Activity[i]) || -->
<!--       grepl("submarine", req_pie$Activity[i]) | -->
<!--       grepl("American", req_pie$Activity[i]) | -->
<!--       grepl("torpedoed", req_pie$Activity[i]) | -->
<!--       grepl("Torpedoed", req_pie$Activity[i]) | -->
<!--       grepl("soldiers", req_pie$Activity[i]) | -->
<!--       grepl("Escaping", req_pie$Activity[i]) | -->
<!--       grepl("Japanese", req_pie$Activity[i]) | -->
<!--       grepl("Japan", req_pie$Activity[i]) | -->
<!--       grepl("Sinking", req_pie$Activity[i]) | -->
<!--       grepl("SS", req_pie$Activity[i]) | -->
<!--       grepl("foundered", req_pie$Activity[i])  | -->
<!--       grepl("US", req_pie$Activity[i]) -->
<!--   ) { -->
<!--     req_pie$Activity[i] <- "murder /  war " -->
<!--   }  -->
<!-- } -->
<!-- ``` -->

